site_name: Ramka
site_url: https://nepnepneppu.github.io/ramka-documentation
repo_name: NepNepNeppu/Ramka
repo_url: https://github.com/NepNepNeppu/Ramka-Framework

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/logo-dark.svg
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: dark-theme
      toggle:
        icon: material/weather-night
        title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: light-theme
      toggle:
        icon: material/weather-sunny
        title: Switch to dark theme
  font:
    text: Montserrat Bold
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
  icon:
    repo: octicons/mark-github-16

nav:
  # - pages/Home.md
  - Home: pages/Home.md
  - API Reference:
    - Scheduler:
      - pages/Scheduler/index.md
    - Components:
      - pages/Components/index.md
    - Internal API:
      - pages/Services-Classes/index.md
    - Embeded:
      - pages/Embeded/index.md


extra_css:
  - stylesheets/extra.css
  - stylesheets/home.css

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg