site_name: Ramka
site_url: https://neptune.us/Ramka/
repo_name: NepNepNeppu/Ramka
repo_url: https://github.com/NepNepNeppu/Ramka-Framework

extra_javascript:
  - smooth-scroll.js

extra_css:
  - style.css
  - base.css

theme:
  name: material
  favicon: assets/logo-dark.svg
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight

nav:
  - Home: Home.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - md_in_html
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg