name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install and Build
      run: |
        npm install
        npm run-script build
    - name: Deploy
      uses: NepNepNeppu/github-pages-deploy-action@releases/v3
    - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
    - run: pip install mkdocs-material
    - run: pip install pillow cairosvg
    - run: mkdocs gh-deploy --force